import sanitizeHtml from 'sanitize-html';

// 1. Define the allowed rules for Email HTML
export const emailSanitizerOptions: sanitizeHtml.IOptions = {
  allowedTags: [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'blockquote',
    'p',
    'a',
    'ul',
    'ol',
    'nl',
    'li',
    'b',
    'i',
    'strong',
    'em',
    'strike',
    'code',
    'hr',
    'br',
    'div',
    'table',
    'thead',
    'caption',
    'tbody',
    'tr',
    'th',
    'td',
    'pre',
    'span',
    'img',
  ],
  allowedAttributes: {
    a: ['href', 'name', 'target'],
    img: ['src', 'alt', 'width', 'height'],
    // Allow inline styles and classes which are heavy in emails
    '*': ['style', 'class', 'id', 'dir', 'lang'],
    table: ['width', 'border', 'cellspacing', 'cellpadding', 'bgcolor'],
    td: ['width', 'bgcolor', 'valign', 'align'],
  },
  allowedSchemes: ['https', 'mailto', 'tel'],
  // Explicitly remove dangerous tags (sanitize-html does this by default, but it's good to be explicit)
  disallowedTagsMode: 'discard',
  allowProtocolRelative: false,
};
