repos:
  ## general
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # pre-commit/pre-commit-hooks@v5.0.0
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b
    hooks:
      # Common errors
      - id: end-of-file-fixer
        exclude_types: [sql]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude_types: [sql, bash, shell]
      - id: check-executables-have-shebangs
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude_types: [sql]
      # Security
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key

  ## secrets detection
  - repo: https://github.com/gitleaks/gitleaks
    # gitleaks/gitleaks@8.28.0
    rev: 4fb43823ef3d152d239e92d7d5cb04783b548062
    hooks:
      - id: gitleaks

  ## terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # antonbabenko/pre-commit-terraform@v1.99.2
    rev: 9aa1e0e7b353dca419a08d3abd2e9f5a0978c383
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - markdown --sort-by required
      - id: terraform_validate
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true
    #      - id: terraform_providers_lock
  #        args:
  #          - --args=-platform=windows_amd64
  #          - --args=-platform=darwin_amd64
  #          - --args=-platform=darwin_arm64
  #          - --args=-platform=linux_amd64
  #          - --args=-platform=linux_arm64

  # commitlint (commit-msg)
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: pnpm exec commitlint --edit
        language: system
        stages: [commit-msg]

  ## node
  - repo: local
    hooks:
      # eslint
      - id: lint
        name: lint
        entry: pnpm eslint --quiet --fix
        language: system
        types_or: [javascript, ts, jsx, tsx]
        stages: [pre-commit]

      # prettier file not checked from eslint
      - id: prettier
        name: prettier
        entry: pnpm prettier --write --log-level silent
        language: system
        types_or: [json, yaml, markdown]
        stages: [pre-commit]

      # typescript type check
      - id: type-check
        name: type-check
        entry: pnpm run type-check
        language: system
        pass_filenames: false
        stages: [pre-commit]
