export const BACKOFF_FACTOR = {
  HIGH_PRIORITY: 2,
  LOW_PRIORITY: 3,
};
export const ESCALATION_THRESHOLD_MINUTES = 15;
export const MILLISECONDS_PER_DAY = 86_400_000;
export const MILLISECONDS_PER_MINUTE = 60_000;
