name: Deploy Lambda Sender

permissions: {}

on:
  push:
    branches:
      - 'main'
    paths:
      - src/onemail/om-lambda-sender/CHANGELOG.md
      - src/onemail/om-common/CHANGELOG.md
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: choice
        required: true
        default: dev
        options:
          - dev
          - uat
          - prod

# Never cancel an in-flight deploy to avoid s3 conflicts
# It prevents issues where multiple commits are pushed in a short time, which would trigger multiple deploys and cancel the previous ones, potentially leaving the app in a broken state if the last deploy fails.
concurrency:
  group: deploy-lambda-sender-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    permissions:
      id-token: write
      contents: read
    with:
      lambda_name: sender
      build_script: build:sender
      package_script: package:sender
      lambda_s3_key_var: LAMBDA_SENDER_KEY
      event_name: ${{ github.event_name }}
      environment_input: ${{ inputs.environment || '' }}
